name: Proof Gen API Deploy docker image to GCP
on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  docker-release:
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/dev') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/master')
    uses: 0xPolygon/pipelines/.github/workflows/gcp_pipeline_release_image.yaml@main
    with:
      image_name: proof-generator-api
      environment: ${{ (github.ref == 'refs/heads/master' && 'prod') || (github.ref == 'refs/heads/dev' && 'staging') }}
