name: Proof Gen API Deploy docker image to GCP
on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  docker-release:
    uses: 0xPolygon/pipelines/.github/workflows/gcp_pipeline_release_image.yaml@main
    with:
      image_name: ${{ github.ref == 'refs/heads/main' && 'proof-generator-api-prod' || 'proof-generator-api-staging' }}
