name: Proof Gen API Deploy docker image to GCP
on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  generate-version:
    uses: 0xPolygon/pipelines/.github/workflows/generate_version.yaml@main

  docker-release:
    needs:
      - generate-version
    uses: 0xPolygon/pipelines/.github/workflows/gcp_pipeline_release_image.yaml@main
    with:
      image_name: ${{ github.ref == 'refs/heads/main' && 'proof-generation-api-prod' || 'proof-generation-api-staging' }}
      image_tag: ${{ needs.generate-version.outputs.version }}
